apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  client-id: OTgxZTU3NTk0MjkyZWRhNGY3MDlmMmQ1OTQyNTc0NmQ=
  javascript-api-key: ZDM5NzIyZTYxY2ZjMTdlODM0ZjYyZDZmYjdlNmEwNTI=
  front-redirect-url: aHR0cHM6Ly9rODFiZGFhOTVjZjU3YS51c2VyLWFwcC5rcmFtcG9saW5lLmNvbQ==